name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup virtual environment
        run: |
          uv venv
          uv pip install -e ".[core,dev]"
      - name: Lint & Typecheck
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run mypy src
      - name: Tests
        run: >
          uv run pytest --cov=src --cov-report=term-missing
          || { code=$?; if [ "$code" -eq 5 ]; then
               echo "No tests found, continuing..."; exit 0;
             else exit "$code"; fi; }
